# Create the Dataframe# 

In [1]:
import pandas as pd
import numpy as mp

In [2]:
# Create a reference to the CSV and import it into a Pandas DataFrame
csv_path = "Resources/student-por.csv"
students_df = pd.read_csv(csv_path)
students_df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        4   0  11  11  
1      5        3      3     1     1      3        2   9  11  11  
2      4        3      2     2     3      3        6  12  13  12  
3      3        2      2     1     1      5        0  14  14  14  
4      4        3      2     1     2      5        0  11  13  13  

[5 rows x 33 columns]

In [3]:
#students_df = students_f[students_f.romantic != 'yes']
#students_df

In [4]:
students_df.describe()

age        Medu        Fedu  traveltime   studytime    failures  \
count  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000   
mean    16.744222    2.514638    2.306626    1.568567    1.930663    0.221880   
std      1.218138    1.134552    1.099931    0.748660    0.829510    0.593235   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    2.000000    1.000000    1.000000    1.000000    0.000000   
50%     17.000000    2.000000    2.000000    1.000000    2.000000    0.000000   
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000   
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000   
mean     3.930663    3.180277    3.184900    1.502311    2.280431    3.536210   
std      0.955717    1.051093    1.175766    0.924834    1.284380    1.446259   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      4.000000    3.000000    2.000000    1.000000    1.000000    2.000000   
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000   
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  649.000000  649.000000  649.000000  649.000000  
mean     3.659476   11.399076   11.570108   11.906009  
std      4.640759    2.745265    2.913639    3.230656  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000   10.000000   10.000000   10.000000  
50%      2.000000   11.000000   11.000000   12.000000  
75%      6.000000   13.000000   13.000000   14.000000  
max     32.000000   19.000000   19.000000   19.000000

In [5]:
students_df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [6]:
# Drop unrelated columns and Walc
students_df = students_df.drop(['school','G1', 'G2', 'G3', 'Walc'], axis=1)
#students_df = students_df.drop(['school','G1', 'G2', 'G3', 'Walc', 'guardian', 'traveltime'], axis=1)
students_df.head()

sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason  \
0   F   18       U     GT3       A     4     4  at_home   teacher  course   
1   F   17       U     GT3       T     1     1  at_home     other  course   
2   F   15       U     LE3       T     1     1  at_home     other   other   
3   F   15       U     GT3       T     4     2   health  services    home   
4   F   16       U     GT3       T     3     3    other     other    home   

   ... nursery  higher  internet  romantic famrel freetime goout Dalc health  \
0  ...     yes     yes        no        no      4        3     4    1      3   
1  ...      no     yes       yes        no      5        3     3    1      3   
2  ...     yes     yes       yes        no      4        3     2    2      3   
3  ...     yes     yes       yes       yes      3        2     2    1      5   
4  ...     yes     yes        no        no      4        3     2    1      5   

  absences  
0        4  
1        2  
2        6  
3        0  
4        0  

[5 rows x 28 columns]

In [7]:
students_df.dtypes

sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
health         int64
absences       int64
dtype: object

In [8]:
students_df.head()

sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason  \
0   F   18       U     GT3       A     4     4  at_home   teacher  course   
1   F   17       U     GT3       T     1     1  at_home     other  course   
2   F   15       U     LE3       T     1     1  at_home     other   other   
3   F   15       U     GT3       T     4     2   health  services    home   
4   F   16       U     GT3       T     3     3    other     other    home   

   ... nursery  higher  internet  romantic famrel freetime goout Dalc health  \
0  ...     yes     yes        no        no      4        3     4    1      3   
1  ...      no     yes       yes        no      5        3     3    1      3   
2  ...     yes     yes       yes        no      4        3     2    2      3   
3  ...     yes     yes       yes       yes      3        2     2    1      5   
4  ...     yes     yes        no        no      4        3     2    1      5   

  absences  
0        4  
1        2  
2        6  
3        0  
4        0  

[5 rows x 28 columns]

In [9]:
# perform get dummies on data set (less Walc) to binary encode for scaling
encoded_students_df = pd.get_dummies(students_df)
encoded_students_df.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
0   18     4     4           2          2         0       4         3      4   
1   17     1     1           1          2         0       5         3      3   
2   15     1     1           1          2         0       4         3      2   
3   15     4     2           1          3         0       3         2      2   
4   16     3     3           1          2         0       4         3      2   

   Dalc  ...  activities_no  activities_yes  nursery_no  nursery_yes  \
0     1  ...              1               0           0            1   
1     1  ...              1               0           1            0   
2     2  ...              1               0           0            1   
3     1  ...              0               1           0            1   
4     1  ...              1               0           0            1   

   higher_no  higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  
0          0           1            1             0            1             0  
1          0           1            0             1            1             0  
2          0           1            0             1            1             0  
3          0           1            0             1            0             1  
4          0           1            1             0            1             0  

[5 rows x 53 columns]

In [10]:
# keep encoded df clean from y data for prediction purposes
working_students_df = encoded_students_df.copy()
working_students_df.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
0   18     4     4           2          2         0       4         3      4   
1   17     1     1           1          2         0       5         3      3   
2   15     1     1           1          2         0       4         3      2   
3   15     4     2           1          3         0       3         2      2   
4   16     3     3           1          2         0       4         3      2   

   Dalc  ...  activities_no  activities_yes  nursery_no  nursery_yes  \
0     1  ...              1               0           0            1   
1     1  ...              1               0           1            0   
2     2  ...              1               0           0            1   
3     1  ...              0               1           0            1   
4     1  ...              1               0           0            1   

   higher_no  higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  
0          0           1            1             0            1             0  
1          0           1            0             1            1             0  
2          0           1            0             1            1             0  
3          0           1            0             1            0             1  
4          0           1            1             0            1             0  

[5 rows x 53 columns]

In [11]:
dalc_col = working_students_df[['Dalc']]
new_df = working_students_df.drop(['Dalc'], axis=1)
new_df['Dalc'] = dalc_col
new_df.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
0   18     4     4           2          2         0       4         3      4   
1   17     1     1           1          2         0       5         3      3   
2   15     1     1           1          2         0       4         3      2   
3   15     4     2           1          3         0       3         2      2   
4   16     3     3           1          2         0       4         3      2   

   health  ...  activities_yes  nursery_no  nursery_yes  higher_no  \
0       3  ...               0           0            1          0   
1       3  ...               0           1            0          0   
2       3  ...               0           0            1          0   
3       5  ...               1           0            1          0   
4       5  ...               0           0            1          0   

   higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  Dalc  
0           1            1             0            1             0     1  
1           1            0             1            1             0     1  
2           1            0             1            1             0     2  
3           1            0             1            0             1     1  
4           1            1             0            1             0     1  

[5 rows x 53 columns]

In [12]:
new_df.columns

Index(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel',
       'freetime', 'goout', 'health', 'absences', 'sex_F', 'sex_M',
       'address_R', 'address_U', 'famsize_GT3', 'famsize_LE3', 'Pstatus_A',
       'Pstatus_T', 'Mjob_at_home', 'Mjob_health', 'Mjob_other',
       'Mjob_services', 'Mjob_teacher', 'Fjob_at_home', 'Fjob_health',
       'Fjob_other', 'Fjob_services', 'Fjob_teacher', 'reason_course',
       'reason_home', 'reason_other', 'reason_reputation', 'guardian_father',
       'guardian_mother', 'guardian_other', 'schoolsup_no', 'schoolsup_yes',
       'famsup_no', 'famsup_yes', 'paid_no', 'paid_yes', 'activities_no',
       'activities_yes', 'nursery_no', 'nursery_yes', 'higher_no',
       'higher_yes', 'internet_no', 'internet_yes', 'romantic_no',
       'romantic_yes', 'Dalc'],
      dtype='object')

In [13]:
# Create the bins in which Drinking levels will be held
bins = [0,1,2,3,4,5]


# Create the names for the five bins
group_names = ["a.Not at all", "b.Slightly", "c.Moderately", "d.Very", "e.Extremely"]


In [14]:
# Create column to contain new bins
new_df["Likelyhood to Drink"] = pd.cut(new_df["Dalc"], bins, labels=group_names)
new_df = new_df.drop(['Dalc'], axis=1)

new_df

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  \
0     18     4     4           2          2         0       4         3   
1     17     1     1           1          2         0       5         3   
2     15     1     1           1          2         0       4         3   
3     15     4     2           1          3         0       3         2   
4     16     3     3           1          2         0       4         3   
..   ...   ...   ...         ...        ...       ...     ...       ...   
644   19     2     3           1          3         1       5         4   
645   18     3     1           1          2         0       4         3   
646   18     1     1           2          2         0       1         1   
647   17     3     1           2          1         0       2         4   
648   18     3     2           3          1         0       4         4   

     goout  health  ...  activities_yes  nursery_no  nursery_yes  higher_no  \
0        4       3  ...               0           0            1          0   
1        3       3  ...               0           1            0          0   
2        2       3  ...               0           0            1          0   
3        2       5  ...               1           0            1          0   
4        2       5  ...               0           0            1          0   
..     ...     ...  ...             ...         ...          ...        ...   
644      2       5  ...               1           1            0          0   
645      4       1  ...               0           0            1          0   
646      1       5  ...               1           0            1          0   
647      5       2  ...               0           1            0          0   
648      1       5  ...               0           1            0          0   

     higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  \
0             1            1             0            1             0   
1             1            0             1            1             0   
2             1            0             1            1             0   
3             1            0             1            0             1   
4             1            1             0            1             0   
..          ...          ...           ...          ...           ...   
644           1            0             1            1             0   
645           1            0             1            1             0   
646           1            1             0            1             0   
647           1            0             1            1             0   
648           1            0             1            1             0   

     Likelyhood to Drink  
0           a.Not at all  
1           a.Not at all  
2             b.Slightly  
3           a.Not at all  
4           a.Not at all  
..                   ...  
644         a.Not at all  
645         a.Not at all  
646         a.Not at all  
647         c.Moderately  
648         c.Moderately  

[649 rows x 53 columns]

In [15]:
# Reformat data (x-inputs, y labels)
data = new_df.values
X = data[:, 0:52]
y = data[:, 52]

y = y.reshape(-1, 1)
print(X)
print(y)

[[18 4 4 ... 0 1 0]
 [17 1 1 ... 1 1 0]
 [15 1 1 ... 1 1 0]
 ...
 [18 1 1 ... 0 1 0]
 [17 3 1 ... 1 1 0]
 [18 3 2 ... 1 1 0]]
[['a.Not at all']
 ['a.Not at all']
 ['b.Slightly']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['b.Slightly']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['b.Slightly']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['b.Slightly']
 ['a.Not at all']
 ['e.Extremely']
 ['c.Moderately']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['b.Slightly']
 ['a.Not at all']
 ['a.Not at all']
 ['b.Slightly']
 ['a.Not at all']
 ['a.Not at all']
 ['a.Not at all']
 ['b.Slightly']
 ['a.No

In [16]:
print(X.shape)
print(y.shape)

(649, 52)
(649, 1)


# Data Processing

In [17]:
from sklearn.preprocessing import LabelEncoder

# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y)
encoded_y = label_encoder.transform(y)

print(encoded_y)


[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 4 2 0 0 0 0 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 2 1 3 0 0 0 0 0 1 4 0 1 1 0 4 0 0 1 0 0 1 1
 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 2 0 0 1 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 2 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 3 4 0 0 0 0
 0 0 1 0 1 0 2 0 0 0 0 0 1 1 1 1 2 1 0 0 0 2 0 0 3 2 1 0 1 0 0 0 1 0 0 0 1
 0 0 0 0 3 0 0 2 0 1 0 1 1 0 1 0 0 0 0 0 0 3 2 0 0 0 2 1 0 0 0 0 0 0 2 1 0
 0 0 0 3 0 1 0 0 1 1 0 0 0 0 0 4 0 0 0 0 3 0 0 0 0 1 0 0 4 0 0 0 0 0 1 0 0
 0 0 0 0 2 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 4 0 1 1 0 1 0 1 0 0 0 0 3 0 1 0 0
 0 0 0 0 0 0 0 0 0 1 2 2 1 0 0 2 0 0 1 0 0 1 0 0 0 0 3 0 1 1 2 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 2 0 0 0 0 1 2 3
 0 1 0 1 1 1 0 1 2 4 0 0 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 1 0 1 1 2 0
 0 0 0 0 0 0 4 0 3 0 0 3 0 0 0 0 0 0 0 1 0 0 0 0 0 1 2 0 0 0 0 0 0 3 1 0 0
 0 1 0 4 0 0 0 0 0 0 0 2 1 4 0 0 0 3 0 1 2 1 0 0 0 0 0 1 0 1 2 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 2 0 3 0 

C:\Users\Sam\Anaconda3\envs\FinalProject\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Sam\Anaconda3\envs\FinalProject\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [18]:
for label, original_class in zip(encoded_y, y):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['b.Slightly']
Encoded Label: 1
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
-------

------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['b.Slightly']
Encoded Label: 1
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['e.Extremely']
Encoded Label: 4
------------
Original Class: ['c.Moderately']
Encoded Label: 2
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['b.Slightly']
Encoded Label: 1
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['b.Slightly']
Encoded Label: 1
------------
Original Class: ['a.Not at all']
Encoded Label: 0
------------
Original Class: ['b.Slightly']
Encoded Label: 1
------------
Original Class: ['b.Slightly']
Encoded Label: 1
------------
Original Class: ['b.Slightly']
Encoded Label: 1
------------
Original Class: ['a.Not at all']
Encoded Label: 0
-----

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, encoded_y, random_state=1, stratify=y)

In [20]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
X_scaler = StandardScaler().fit(X_train)

In [21]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [22]:
from keras.utils import to_categorical

# One-hot encoding
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)
y_train_categorical

Using TensorFlow backend.


array([[0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)

# Create Deep Learning Model

In [23]:
from tensorflow.keras.models import Sequential

model = Sequential()

In [24]:
from tensorflow.keras.layers import Dense
number_inputs = 52

number_hidden_nodes = 100
#number_hidden_nodes = 156
#number_hidden_nodes = 850
model.add(Dense(units=number_hidden_nodes,
                activation='relu', input_dim=number_inputs))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [25]:
# add another layer??

number_layer_classes = 100
model.add(Dense(units=number_layer_classes, activation='relu'))
number_layer_classes = 100
model.add(Dense(units=number_layer_classes, activation='relu'))

In [26]:
# add another layer??
number_classes = 5
model.add(Dense(units=number_classes, activation='softmax'))


In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               5300      
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 505       
Total params: 26,005
Trainable params: 26,005
Non-trainable params: 0
_________________________________________________________________


In [28]:
# Use categorical crossentropy for categorical data and mean squared error for regression
# Hint: your output layer in this example is using software for logistic regression (categorical)
# If your output layer activation was `linear` then you may want to use `mse` for loss
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [29]:
# Fit (train) the model
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
486/486 - 0s - loss: 1.2160 - acc: 0.6029
Epoch 2/100
486/486 - 0s - loss: 0.8855 - acc: 0.6975
Epoch 3/100
486/486 - 0s - loss: 0.7883 - acc: 0.7140
Epoch 4/100
486/486 - 0s - loss: 0.7122 - acc: 0.7346
Epoch 5/100
486/486 - 0s - loss: 0.6492 - acc: 0.7572
Epoch 6/100
486/486 - 0s - loss: 0.5830 - acc: 0.7757
Epoch 7/100
486/486 - 0s - loss: 0.5243 - acc: 0.8210
Epoch 8/100
486/486 - 0s - loss: 0.4658 - acc: 0.8374
Epoch 9/100
486/486 - 0s - loss: 0.4023 - acc: 0.8580
Epoch 10/100
486/486 - 0s - loss: 0.3406 - acc: 0.8930
Epoch 11/100
486/486 - 0s - loss: 0.2830 - acc: 0.8971
Epoch 12/100
486/486 - 0s - loss: 0.2286 - acc: 0.9444
Epoch 13/100
486/486 - 0s - loss: 0.1794 - acc: 0.9691
Epoch 14/100
486/486 - 0s - loss: 0.1446 - acc: 0.9856
Epoch 15/100
486/486 - 0s - loss: 0.1111 - acc: 0.9918
Epoch 16/100
486/486 - 0s - loss: 0.0868 - acc: 0.9979
Epoch 17/100
486/486 - 0s - loss: 0.0644 - acc: 0.9938
Epoch 18/100
486/486 - 0s - loss: 0.0514 - acc: 1.0000
Epoch 19/100
486/48

In [30]:
# Evaluate the model using the testing data
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

163/163 - 0s - loss: 3.7009 - acc: 0.5951
Loss: 3.7008984001136267, Accuracy: 0.5950919985771179


In [31]:
encoded_predictions = model.predict_classes(X_test_scaled[:3])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [32]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:3])}")

Predicted classes: ['a.Not at all' 'd.Very' 'a.Not at all']
Actual Labels: [1, 0, 0]


In [33]:
#Save the model
model.save("students_deep_learning_dalc_trained.h5")


In [34]:
data = {'Deep Learning Accuracy': [model_accuracy]}
df = pd.DataFrame(data=data)
df

Deep Learning Accuracy
0                0.595092