# Final Project #

## Create the DataFrame ##

In [1]:
import pandas as pd
import numpy as mp

In [2]:
# Create a reference to the CSV and import it into a Pandas DataFrame
csv_path = "Resources/student-por.csv"
students_df = pd.read_csv(csv_path)
students_df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        4   0  11  11  
1      5        3      3     1     1      3        2   9  11  11  
2      4        3      2     2     3      3        6  12  13  12  
3      3        2      2     1     1      5        0  14  14  14  
4      4        3      2     1     2      5        0  11  13  13  

[5 rows x 33 columns]

In [3]:
students_address_df = students_df[students_df.address != 'U']
students_address_df.head()

school sex  age address famsize Pstatus  Medu  Fedu      Mjob     Fjob  \
24     GP   F   15       R     GT3       T     2     4  services   health   
32     GP   M   15       R     GT3       T     4     3   teacher  at_home   
37     GP   M   16       R     GT3       A     4     4     other  teacher   
38     GP   F   15       R     GT3       T     3     4  services   health   
39     GP   F   15       R     GT3       T     2     2   at_home    other   

    ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
24  ...      4        3      2     1     1      5        2  10  11  10  
32  ...      4        5      2     1     1      5        0  13  14  15  
37  ...      2        4      3     1     1      5        4  13  13  13  
38  ...      4        3      2     1     1      5        2  11  12  12  
39  ...      4        3      1     1     1      2        8  14  13  12  

[5 rows x 33 columns]

In [4]:
students_address_df.describe()

age        Medu        Fedu  traveltime   studytime    failures  \
count  197.000000  197.000000  197.000000  197.000000  197.000000  197.000000   
mean    16.791878    2.187817    2.071066    1.959391    1.852792    0.279188   
std      1.229873    1.111284    1.076192    0.838107    0.847358    0.645410   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    1.000000    1.000000    1.000000    1.000000    0.000000   
50%     17.000000    2.000000    2.000000    2.000000    2.000000    0.000000   
75%     18.000000    3.000000    3.000000    2.000000    2.000000    0.000000   
max     21.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  197.000000  197.000000  197.000000  197.000000  197.000000  197.000000   
mean     3.979695    3.238579    3.157360    1.568528    2.304569    3.527919   
std      0.931092    1.128903    1.203994    0.948481    1.293086    1.430528   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      4.000000    3.000000    2.000000    1.000000    1.000000    2.000000   
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000   
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  197.000000  197.000000  197.000000  197.000000  
mean     3.142132   10.746193   10.888325   11.086294  
std      3.934424    2.724894    3.101632    3.605221  
min      0.000000    4.000000    0.000000    0.000000  
25%      0.000000    9.000000    9.000000   10.000000  
50%      2.000000   10.000000   11.000000   11.000000  
75%      4.000000   13.000000   13.000000   13.000000  
max     21.000000   18.000000   19.000000   19.000000

In [5]:
students_address_df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [6]:
# Drop unrelated columns and Walc
students_address_df = students_address_df.drop(['school','G1', 'G2', 'G3', 'Walc'], axis=1)
students_address_df.head()

sex  age address famsize Pstatus  Medu  Fedu      Mjob     Fjob  \
24   F   15       R     GT3       T     2     4  services   health   
32   M   15       R     GT3       T     4     3   teacher  at_home   
37   M   16       R     GT3       A     4     4     other  teacher   
38   F   15       R     GT3       T     3     4  services   health   
39   F   15       R     GT3       T     2     2   at_home    other   

        reason  ... nursery  higher  internet  romantic famrel freetime goout  \
24      course  ...     yes     yes       yes        no      4        3     2   
32      course  ...     yes     yes       yes       yes      4        5     2   
37  reputation  ...     yes     yes       yes       yes      2        4     3   
38      course  ...     yes     yes       yes        no      4        3     2   
39  reputation  ...     yes     yes        no        no      4        3     1   

   Dalc health absences  
24    1      5        2  
32    1      5        0  
37    1      5        4  
38    1      5        2  
39    1      2        8  

[5 rows x 28 columns]

In [7]:
# perform get dummies on data set (less Walc) to binary encode for scaling
encoded_address_df = pd.get_dummies(students_address_df)
encoded_address_df.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
24   15     2     4           1          3         0       4         3      2   
32   15     4     3           1          2         0       4         5      2   
37   16     4     4           2          3         0       2         4      3   
38   15     3     4           1          3         0       4         3      2   
39   15     2     2           1          1         0       4         3      1   

    Dalc  ...  activities_no  activities_yes  nursery_no  nursery_yes  \
24     1  ...              0               1           0            1   
32     1  ...              0               1           0            1   
37     1  ...              0               1           0            1   
38     1  ...              0               1           0            1   
39     1  ...              0               1           0            1   

    higher_no  higher_yes  internet_no  internet_yes  romantic_no  \
24          0           1            0             1            1   
32          0           1            0             1            0   
37          0           1            0             1            0   
38          0           1            0             1            1   
39          0           1            1             0            1   

    romantic_yes  
24             0  
32             1  
37             1  
38             0  
39             0  

[5 rows x 52 columns]

In [8]:
# keep encoded df clean from y data for prediction purposes
working_students_df = encoded_address_df.copy()
working_students_df.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
24   15     2     4           1          3         0       4         3      2   
32   15     4     3           1          2         0       4         5      2   
37   16     4     4           2          3         0       2         4      3   
38   15     3     4           1          3         0       4         3      2   
39   15     2     2           1          1         0       4         3      1   

    Dalc  ...  activities_no  activities_yes  nursery_no  nursery_yes  \
24     1  ...              0               1           0            1   
32     1  ...              0               1           0            1   
37     1  ...              0               1           0            1   
38     1  ...              0               1           0            1   
39     1  ...              0               1           0            1   

    higher_no  higher_yes  internet_no  internet_yes  romantic_no  \
24          0           1            0             1            1   
32          0           1            0             1            0   
37          0           1            0             1            0   
38          0           1            0             1            1   
39          0           1            1             0            1   

    romantic_yes  
24             0  
32             1  
37             1  
38             0  
39             0  

[5 rows x 52 columns]

In [9]:
Dalc_col = working_students_df[['Dalc']]
new_df = working_students_df.drop(['Dalc'], axis=1)
new_df['Dalc'] = Dalc_col
new_df.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
24   15     2     4           1          3         0       4         3      2   
32   15     4     3           1          2         0       4         5      2   
37   16     4     4           2          3         0       2         4      3   
38   15     3     4           1          3         0       4         3      2   
39   15     2     2           1          1         0       4         3      1   

    health  ...  activities_yes  nursery_no  nursery_yes  higher_no  \
24       5  ...               1           0            1          0   
32       5  ...               1           0            1          0   
37       5  ...               1           0            1          0   
38       5  ...               1           0            1          0   
39       2  ...               1           0            1          0   

    higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  Dalc  
24           1            0             1            1             0     1  
32           1            0             1            0             1     1  
37           1            0             1            0             1     1  
38           1            0             1            1             0     1  
39           1            1             0            1             0     1  

[5 rows x 52 columns]

In [10]:
new_df.dtypes

age                  int64
Medu                 int64
Fedu                 int64
traveltime           int64
studytime            int64
failures             int64
famrel               int64
freetime             int64
goout                int64
health               int64
absences             int64
sex_F                uint8
sex_M                uint8
address_R            uint8
famsize_GT3          uint8
famsize_LE3          uint8
Pstatus_A            uint8
Pstatus_T            uint8
Mjob_at_home         uint8
Mjob_health          uint8
Mjob_other           uint8
Mjob_services        uint8
Mjob_teacher         uint8
Fjob_at_home         uint8
Fjob_health          uint8
Fjob_other           uint8
Fjob_services        uint8
Fjob_teacher         uint8
reason_course        uint8
reason_home          uint8
reason_other         uint8
reason_reputation    uint8
guardian_father      uint8
guardian_mother      uint8
guardian_other       uint8
schoolsup_no         uint8
schoolsup_yes        uint8
f

In [11]:
# Create the bins in which Drinking levels will be held
bins = [0,1,2,3,4,5]

# Create the names for the five bins
group_names = ["A.Not at all", "B.Slightly", "C.Moderately", "D.Very", "E.Extremely"]

In [12]:
# Create column to contain new bins
new_df["Likelyhood to Drink"] = pd.cut(new_df["Dalc"], bins, labels=group_names)
new_df = new_df.drop(['Dalc'], axis=1)

new_df

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  \
24    15     2     4           1          3         0       4         3   
32    15     4     3           1          2         0       4         5   
37    16     4     4           2          3         0       2         4   
38    15     3     4           1          3         0       4         3   
39    15     2     2           1          1         0       4         3   
..   ...   ...   ...         ...        ...       ...     ...       ...   
640   18     4     2           2          1         1       5         4   
641   18     2     2           2          3         0       5         3   
643   18     4     4           3          1         0       4         4   
644   19     2     3           1          3         1       5         4   
648   18     3     2           3          1         0       4         4   

     goout  health  ...  activities_yes  nursery_no  nursery_yes  higher_no  \
24       2       5  ...               1           0            1          0   
32       2       5  ...               1           0            1          0   
37       3       5  ...               1           0            1          0   
38       2       5  ...               1           0            1          0   
39       1       2  ...               1           0            1          0   
..     ...     ...  ...             ...         ...          ...        ...   
640      3       3  ...               0           0            1          0   
641      3       4  ...               0           0            1          0   
643      3       5  ...               1           0            1          0   
644      2       5  ...               1           1            0          0   
648      1       5  ...               0           1            0          0   

     higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  \
24            1            0             1            1             0   
32            1            0             1            0             1   
37            1            0             1            0             1   
38            1            0             1            1             0   
39            1            1             0            1             0   
..          ...          ...           ...          ...           ...   
640           1            1             0            1             0   
641           1            1             0            1             0   
643           1            0             1            0             1   
644           1            0             1            1             0   
648           1            0             1            1             0   

     Likelyhood to Drink  
24          A.Not at all  
32          A.Not at all  
37          A.Not at all  
38          A.Not at all  
39          A.Not at all  
..                   ...  
640               D.Very  
641         A.Not at all  
643           B.Slightly  
644         A.Not at all  
648         C.Moderately  

[197 rows x 52 columns]

In [13]:
working_students_df.columns

Index(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel',
       'freetime', 'goout', 'Dalc', 'health', 'absences', 'sex_F', 'sex_M',
       'address_R', 'famsize_GT3', 'famsize_LE3', 'Pstatus_A', 'Pstatus_T',
       'Mjob_at_home', 'Mjob_health', 'Mjob_other', 'Mjob_services',
       'Mjob_teacher', 'Fjob_at_home', 'Fjob_health', 'Fjob_other',
       'Fjob_services', 'Fjob_teacher', 'reason_course', 'reason_home',
       'reason_other', 'reason_reputation', 'guardian_father',
       'guardian_mother', 'guardian_other', 'schoolsup_no', 'schoolsup_yes',
       'famsup_no', 'famsup_yes', 'paid_no', 'paid_yes', 'activities_no',
       'activities_yes', 'nursery_no', 'nursery_yes', 'higher_no',
       'higher_yes', 'internet_no', 'internet_yes', 'romantic_no',
       'romantic_yes'],
      dtype='object')

In [14]:
# Reformat data (x-inputs, y labels)
data = new_df.values
X = data[:, 0:51]
y = data[:, 51]

y = y.reshape(-1, 1)
print(X)
print(y)

[[15 2 4 ... 1 1 0]
 [15 4 3 ... 1 0 1]
 [16 4 4 ... 1 0 1]
 ...
 [18 4 4 ... 1 0 1]
 [19 2 3 ... 1 1 0]
 [18 3 2 ... 1 1 0]]
[['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['B.Slightly']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['C.Moderately']
 ['A.Not at all']
 ['C.Moderately']
 ['C.Moderately']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at all']
 ['A.Not at all']
 ['A.Not at all']
 ['B.Slightly']
 ['A.Not at 

In [15]:
print(X.shape)
print(y.shape)

(197, 51)
(197, 1)


In [16]:
from sklearn.preprocessing import LabelEncoder

# Step 1: Label-encode data set
label_encoder = LabelEncoder()

label_encoder.fit(y)
encoded_y = label_encoder.transform(y)

print(encoded_y)

[0 0 0 0 0 1 0 1 1 0 0 2 0 0 0 1 1 0 1 0 0 0 1 0 2 0 0 1 0 0 2 0 2 2 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 2 1 0 1 0 3 0 0 0 0 0 0 0 1 1 4 1 0 0 1
 0 4 0 3 0 0 1 0 0 0 0 1 2 0 0 0 0 0 0 0 0 1 4 0 0 0 0 0 4 0 0 0 3 0 1 2 0
 0 1 0 2 0 0 0 0 0 0 0 2 0 0 0 1 2 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 2 1 1 1
 0 1 0 2 0 0 0 1 1 1 1 1 1 2 4 2 2 0 0 1 0 0 0 2 0 0 0 0 0 0 0 0 1 0 3 1 0
 0 0 0 2 1 0 0 3 0 1 0 2]


C:\Users\jener\Anaconda3\envs\PythonWebMongo\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jener\Anaconda3\envs\PythonWebMongo\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [17]:
for label, original_class in zip(encoded_y, y):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['C.Moderately']
Encoded Label: 2
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['A.Not at all']
Encoded Label: 0
------------
Original Class: ['B.Slightly']
Encoded Label: 1
------------


In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, encoded_y, random_state=5)

## Data Preprocessing ##

In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
X_scaler = StandardScaler().fit(X_train)

In [20]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [21]:
from keras.utils import to_categorical

# One-hot encoding
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

Using TensorFlow backend.


## Create Deep Learning Model ##

In [22]:
from tensorflow.keras.models import Sequential

model = Sequential()

In [23]:
from tensorflow.keras.layers import Dense
number_inputs = 51

number_hidden_nodes = 150
model.add(Dense(units=number_hidden_nodes,
                activation='relu', input_dim=number_inputs))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [24]:
# add another layer??
number_layer_classes = 10
model.add(Dense(units=number_layer_classes, activation='relu'))
model.add(Dense(units=number_layer_classes, activation='relu'))
model.add(Dense(units=number_layer_classes, activation='relu'))
# model.add(Dense(units=number_layer_classes, activation='relu'))
# model.add(Dense(units=number_layer_classes, activation='relu'))

In [25]:
# add another layer??
number_classes = 5
model.add(Dense(units=number_classes, activation='softmax'))

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 150)               7800      
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1510      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_3 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_4 (Dense)              (None, 5)                 55        
Total params: 9,585
Trainable params: 9,585
Non-trainable params: 0
_________________________________________________________________


In [27]:
# Use categorical crossentropy for categorical data and mean squared error for regression
# Hint: your output layer in this example is using software for logistic regression (categorical)
# If your output layer activation was `linear` then you may want to use `mse` for loss
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [28]:
# Fit (train) the model
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=50,
    shuffle=True,
    verbose=2
)

Epoch 1/50
147/147 - 0s - loss: 1.5969 - acc: 0.2585
Epoch 2/50
147/147 - 0s - loss: 1.4484 - acc: 0.5714
Epoch 3/50
147/147 - 0s - loss: 1.3733 - acc: 0.6259
Epoch 4/50
147/147 - 0s - loss: 1.2960 - acc: 0.6463
Epoch 5/50
147/147 - 0s - loss: 1.2094 - acc: 0.6531
Epoch 6/50
147/147 - 0s - loss: 1.1219 - acc: 0.6531
Epoch 7/50
147/147 - 0s - loss: 1.0441 - acc: 0.6531
Epoch 8/50
147/147 - 0s - loss: 0.9795 - acc: 0.6531
Epoch 9/50
147/147 - 0s - loss: 0.9192 - acc: 0.6599
Epoch 10/50
147/147 - 0s - loss: 0.8708 - acc: 0.6735
Epoch 11/50
147/147 - 0s - loss: 0.8267 - acc: 0.6735
Epoch 12/50
147/147 - 0s - loss: 0.7869 - acc: 0.6735
Epoch 13/50
147/147 - 0s - loss: 0.7499 - acc: 0.6735
Epoch 14/50
147/147 - 0s - loss: 0.7159 - acc: 0.6803
Epoch 15/50
147/147 - 0s - loss: 0.6826 - acc: 0.6939
Epoch 16/50
147/147 - 0s - loss: 0.6480 - acc: 0.7075
Epoch 17/50
147/147 - 0s - loss: 0.6148 - acc: 0.7279
Epoch 18/50
147/147 - 0s - loss: 0.5823 - acc: 0.7551
Epoch 19/50
147/147 - 0s - loss: 0.55

## Quantify Trained Model ##

In [29]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

50/50 - 0s - loss: 1.8212 - acc: 0.6200
Normal Neural Network - Loss: 1.821169900894165, Accuracy: 0.6200000047683716


## Save Trained Model ##

In [30]:
# Save the model
# model.save("students_deep_learning_trained.h5")

In [31]:
# import numpy as np
# predict_student = encoded_students_df.iloc[4]

# predict_student = np.expand_dims(predict_student, axis=0)

# model.predict_classes(predict_student)
# # predict

In [32]:
data = {'Deep Learning (Rural) Accuracy': [model_accuracy]}
df = pd.DataFrame(data=data)
df

Deep Learning (Rural) Accuracy
0                            0.62