# Final Project #

## Create the DataFrame ##

In [1]:
import pandas as pd
import numpy as mp

In [2]:
# Create a reference to the CSV and import it into a Pandas DataFrame
csv_path = "Resources/student-por.csv"
students_df = pd.read_csv(csv_path)
students_df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        4   0  11  11  
1      5        3      3     1     1      3        2   9  11  11  
2      4        3      2     2     3      3        6  12  13  12  
3      3        2      2     1     1      5        0  14  14  14  
4      4        3      2     1     2      5        0  11  13  13  

[5 rows x 33 columns]

In [3]:
students_df.describe()

age        Medu        Fedu  traveltime   studytime    failures  \
count  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000   
mean    16.744222    2.514638    2.306626    1.568567    1.930663    0.221880   
std      1.218138    1.134552    1.099931    0.748660    0.829510    0.593235   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    2.000000    1.000000    1.000000    1.000000    0.000000   
50%     17.000000    2.000000    2.000000    1.000000    2.000000    0.000000   
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000   
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000   
mean     3.930663    3.180277    3.184900    1.502311    2.280431    3.536210   
std      0.955717    1.051093    1.175766    0.924834    1.284380    1.446259   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      4.000000    3.000000    2.000000    1.000000    1.000000    2.000000   
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000   
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  649.000000  649.000000  649.000000  649.000000  
mean     3.659476   11.399076   11.570108   11.906009  
std      4.640759    2.745265    2.913639    3.230656  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000   10.000000   10.000000   10.000000  
50%      2.000000   11.000000   11.000000   12.000000  
75%      6.000000   13.000000   13.000000   14.000000  
max     32.000000   19.000000   19.000000   19.000000

In [4]:
students_df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [5]:
# # need to pull out Walc before get dummies on dataset - need Walc later to bin
# pulled_Walc = students_df[['Walc']].copy()
# pulled_Walc

In [6]:
# Drop unrelated columns and Walc
students_df = students_df.drop(['school','G1', 'G2', 'G3', 'Dalc'], axis=1)
students_df.head()

sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason  \
0   F   18       U     GT3       A     4     4  at_home   teacher  course   
1   F   17       U     GT3       T     1     1  at_home     other  course   
2   F   15       U     LE3       T     1     1  at_home     other   other   
3   F   15       U     GT3       T     4     2   health  services    home   
4   F   16       U     GT3       T     3     3    other     other    home   

   ... nursery  higher  internet  romantic famrel freetime goout Walc health  \
0  ...     yes     yes        no        no      4        3     4    1      3   
1  ...      no     yes       yes        no      5        3     3    1      3   
2  ...     yes     yes       yes        no      4        3     2    3      3   
3  ...     yes     yes       yes       yes      3        2     2    1      5   
4  ...     yes     yes        no        no      4        3     2    2      5   

  absences  
0        4  
1        2  
2        6  
3        0  
4        0  

[5 rows x 28 columns]

In [7]:
students_df.dtypes

sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Walc           int64
health         int64
absences       int64
dtype: object

In [8]:
students_df.head()

sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason  \
0   F   18       U     GT3       A     4     4  at_home   teacher  course   
1   F   17       U     GT3       T     1     1  at_home     other  course   
2   F   15       U     LE3       T     1     1  at_home     other   other   
3   F   15       U     GT3       T     4     2   health  services    home   
4   F   16       U     GT3       T     3     3    other     other    home   

   ... nursery  higher  internet  romantic famrel freetime goout Walc health  \
0  ...     yes     yes        no        no      4        3     4    1      3   
1  ...      no     yes       yes        no      5        3     3    1      3   
2  ...     yes     yes       yes        no      4        3     2    3      3   
3  ...     yes     yes       yes       yes      3        2     2    1      5   
4  ...     yes     yes        no        no      4        3     2    2      5   

  absences  
0        4  
1        2  
2        6  
3        0  
4        0  

[5 rows x 28 columns]

In [9]:
# perform get dummies on data set (less Walc) to binary encode for scaling
# encoded_students_df = pd.get_dummies(students_df['sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 
#                                                  'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 
#                                                  'higher', 'internet', 'romantic'])
encoded_students_df = pd.get_dummies(students_df)

encoded_students_df.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
0   18     4     4           2          2         0       4         3      4   
1   17     1     1           1          2         0       5         3      3   
2   15     1     1           1          2         0       4         3      2   
3   15     4     2           1          3         0       3         2      2   
4   16     3     3           1          2         0       4         3      2   

   Walc  ...  activities_no  activities_yes  nursery_no  nursery_yes  \
0     1  ...              1               0           0            1   
1     1  ...              1               0           1            0   
2     3  ...              1               0           0            1   
3     1  ...              0               1           0            1   
4     2  ...              1               0           0            1   

   higher_no  higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  
0          0           1            1             0            1             0  
1          0           1            0             1            1             0  
2          0           1            0             1            1             0  
3          0           1            0             1            0             1  
4          0           1            1             0            1             0  

[5 rows x 53 columns]

In [10]:
# keep encoded df clean from y data for prediction purposes
working_students_df = encoded_students_df.copy()
working_students_df.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
0   18     4     4           2          2         0       4         3      4   
1   17     1     1           1          2         0       5         3      3   
2   15     1     1           1          2         0       4         3      2   
3   15     4     2           1          3         0       3         2      2   
4   16     3     3           1          2         0       4         3      2   

   Walc  ...  activities_no  activities_yes  nursery_no  nursery_yes  \
0     1  ...              1               0           0            1   
1     1  ...              1               0           1            0   
2     3  ...              1               0           0            1   
3     1  ...              0               1           0            1   
4     2  ...              1               0           0            1   

   higher_no  higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  
0          0           1            1             0            1             0  
1          0           1            0             1            1             0  
2          0           1            0             1            1             0  
3          0           1            0             1            0             1  
4          0           1            1             0            1             0  

[5 rows x 53 columns]

In [42]:
walc_col = working_students_df[['Walc']]
new_df = working_students_df.drop(['Walc'], axis=1)
new_df.append

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
0   18     4     4           2          2         0       4         3      4   
1   17     1     1           1          2         0       5         3      3   
2   15     1     1           1          2         0       4         3      2   
3   15     4     2           1          3         0       3         2      2   
4   16     3     3           1          2         0       4         3      2   

   health  ...  activities_no  activities_yes  nursery_no  nursery_yes  \
0       3  ...              1               0           0            1   
1       3  ...              1               0           1            0   
2       3  ...              1               0           0            1   
3       5  ...              0               1           0            1   
4       5  ...              1               0           0            1   

   higher_no  higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  
0          0           1            1             0            1             0  
1          0           1            0             1            1             0  
2          0           1            0             1            1             0  
3          0           1            0             1            0             1  
4          0           1            1             0            1             0  

[5 rows x 52 columns]

In [22]:
column_list = working_students_df.columns
front = column_list[0:8]
back = column_list[9:]
new_list = front.append(back)
new_list

Index(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel',
       'freetime', 'Walc', 'health', 'absences', 'sex_F', 'sex_M', 'address_R',
       'address_U', 'famsize_GT3', 'famsize_LE3', 'Pstatus_A', 'Pstatus_T',
       'Mjob_at_home', 'Mjob_health', 'Mjob_other', 'Mjob_services',
       'Mjob_teacher', 'Fjob_at_home', 'Fjob_health', 'Fjob_other',
       'Fjob_services', 'Fjob_teacher', 'reason_course', 'reason_home',
       'reason_other', 'reason_reputation', 'guardian_father',
       'guardian_mother', 'guardian_other', 'schoolsup_no', 'schoolsup_yes',
       'famsup_no', 'famsup_yes', 'paid_no', 'paid_yes', 'activities_no',
       'activities_yes', 'nursery_no', 'nursery_yes', 'higher_no',
       'higher_yes', 'internet_no', 'internet_yes', 'romantic_no',
       'romantic_yes'],
      dtype='object')

In [12]:
# working_students_df['Walc'] = working_students_df.Walc(52)

In [13]:
# working_students_df = working_students_df(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel',
#        'freetime', 'goout', 'health', 'absences', 'sex_F', 'sex_M',
#        'address_R', 'address_U', 'famsize_GT3', 'famsize_LE3', 'Pstatus_A',
#        'Pstatus_T', 'Mjob_at_home', 'Mjob_health', 'Mjob_other',
#        'Mjob_services', 'Mjob_teacher', 'Fjob_at_home', 'Fjob_health',
#        'Fjob_other', 'Fjob_services', 'Fjob_teacher', 'reason_course',
#        'reason_home', 'reason_other', 'reason_reputation', 'guardian_father',
#        'guardian_mother', 'guardian_other', 'schoolsup_no', 'schoolsup_yes',
#        'famsup_no', 'famsup_yes', 'paid_no', 'paid_yes', 'activities_no',
#        'activities_yes', 'nursery_no', 'nursery_yes', 'higher_no',
#        'higher_yes', 'internet_no', 'internet_yes', 'romantic_no',
#        'romantic_yes', 'Walc'], ascending=[1, 0])

In [14]:
working_students_df.dtypes

age                  int64
Medu                 int64
Fedu                 int64
traveltime           int64
studytime            int64
failures             int64
famrel               int64
freetime             int64
goout                int64
Walc                 int64
health               int64
absences             int64
sex_F                uint8
sex_M                uint8
address_R            uint8
address_U            uint8
famsize_GT3          uint8
famsize_LE3          uint8
Pstatus_A            uint8
Pstatus_T            uint8
Mjob_at_home         uint8
Mjob_health          uint8
Mjob_other           uint8
Mjob_services        uint8
Mjob_teacher         uint8
Fjob_at_home         uint8
Fjob_health          uint8
Fjob_other           uint8
Fjob_services        uint8
Fjob_teacher         uint8
reason_course        uint8
reason_home          uint8
reason_other         uint8
reason_reputation    uint8
guardian_father      uint8
guardian_mother      uint8
guardian_other       uint8
s

In [15]:
# pulled_Walc.dtypes

In [16]:
# # insert Walc back into encoded dataframe
# working_students_df['Walc']=pulled_Walc['Walc']
# working_students_df

In [17]:
# Create the bins in which Drinking levels will be held
# bins = [0,1,2,3,4,5]

# # Create the names for the five bins
# group_names = ["Not at all", "Slightly", "Moderately", "Very", "Extremely"]

In [18]:
# # Create column to contain new bins
# working_students_df["Likelyhood to Drink"] = pd.cut(working_students_df["Walc"], bins, labels=group_names)
# working_students_df = working_students_df.drop(['Walc'], axis=1)

# working_students_df

In [23]:
# Reformat data (x-inputs, y labels)
data = working_students_df.values
X = data[:, 0:8]
y = data[:, 9]

y = y.reshape(-1, 1)
print(X)
print(y)

[[18  4  4 ...  0  4  3]
 [17  1  1 ...  0  5  3]
 [15  1  1 ...  0  4  3]
 ...
 [18  1  1 ...  0  1  1]
 [17  3  1 ...  0  2  4]
 [18  3  2 ...  0  4  4]]
[[1]
 [1]
 [3]
 [1]
 [2]
 [2]
 [1]
 [1]
 [1]
 [1]
 [2]
 [1]
 [3]
 [2]
 [1]
 [2]
 [2]
 [1]
 [4]
 [3]
 [1]
 [1]
 [3]
 [4]
 [1]
 [3]
 [2]
 [4]
 [1]
 [5]
 [4]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [4]
 [1]
 [1]
 [2]
 [1]
 [4]
 [1]
 [2]
 [1]
 [3]
 [1]
 [4]
 [3]
 [4]
 [1]
 [1]
 [1]
 [1]
 [1]
 [3]
 [5]
 [1]
 [4]
 [4]
 [2]
 [5]
 [2]
 [3]
 [3]
 [1]
 [1]
 [4]
 [2]
 [4]
 [3]
 [1]
 [3]
 [1]
 [2]
 [3]
 [2]
 [1]
 [3]
 [3]
 [3]
 [2]
 [3]
 [1]
 [5]
 [3]
 [3]
 [3]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [1]
 [5]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [5]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [1]
 [1]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [1]
 [2]
 [1]
 [1]
 [5]
 [2]
 [2]
 [3]
 [2]
 [2]
 [3]
 [4]
 [1]
 [1]
 [1]
 [1]
 [4]
 [1]
 [5]
 [1]
 [2]
 [1]
 [3]
 [1]
 [1]
 [1]
 [3]
 [3]
 [2]
 [1]
 [3]
 [2]
 [2]
 [1]
 [1]
 [1]
 [4]
 [1]
 [5]
 [5]
 [5]
 [3]
 [1]
 [1]
 [1]

In [ ]:
print(X.shape)
print(y.shape)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

## Data Preprocessing ##

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
X_scaler = MinMaxScaler().fit(X_train)

In [ ]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)

encoded_y_train = label_encoder.transform(y_train)
label_encoder.fit(y_test)

encoded_y_test = label_encoder.transform(y_test)
print(encoded_y_train)

# print(encoded_y_test)

In [ ]:
for label, original_class in zip(encoded_y_train, y):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

In [ ]:
from keras.utils import to_categorical

# One-hot encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

## Create Deep Learning Model ##

In [ ]:
from tensorflow.keras.models import Sequential

model = Sequential()

In [ ]:
from tensorflow.keras.layers import Dense
number_inputs = 52

number_hidden_nodes = 150
model.add(Dense(units=number_hidden_nodes,
                activation='relu', input_dim=number_inputs))

In [ ]:
# add another layer??
number_layer_classes = 7
model.add(Dense(units=number_layer_classes, activation='relu'))
model.add(Dense(units=number_layer_classes, activation='relu'))
model.add(Dense(units=number_layer_classes, activation='relu'))
# model.add(Dense(units=number_layer_classes, activation='relu'))
# model.add(Dense(units=number_layer_classes, activation='relu'))
# model.add(Dense(units=number_classes, activation='relu'))
# model.add(Dense(units=number_classes, activation='relu'))
# model.add(Dense(units=number_classes, activation='relu'))
# model.add(Dense(units=number_classes, activation='relu'))

In [ ]:
# add another layer??
number_classes = 5
model.add(Dense(units=number_classes, activation='softmax'))

In [ ]:
model.summary()

In [ ]:
# Use categorical crossentropy for categorical data and mean squared error for regression
# Hint: your output layer in this example is using software for logistic regression (categorical)
# If your output layer activation was `linear` then you may want to use `mse` for loss
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
X_train_scaled.shape=(486,52)

In [ ]:
# Fit (train) the model
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=40,
    shuffle=True,
    verbose=2
)

## Quantify Trained Model ##

In [ ]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

## Save Trained Model ##

In [ ]:
# Save the model
# model.save("students_deep_learning_trained2.h5")

In [ ]:
import numpy as np
predict_student = encoded_students_df.iloc[4]

predict_student = np.expand_dims(predict_student, axis=0)

model.predict_classes(predict_student)
# predict