# Final Project #

## Create the DataFrame ##

In [1]:
import pandas as pd

In [2]:
# Create a reference to the CSV and import it into a Pandas DataFrame
csv_path = "Resources/student-por.csv"
students_df = pd.read_csv(csv_path)
students_df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        4   0  11  11  
1      5        3      3     1     1      3        2   9  11  11  
2      4        3      2     2     3      3        6  12  13  12  
3      3        2      2     1     1      5        0  14  14  14  
4      4        3      2     1     2      5        0  11  13  13  

[5 rows x 33 columns]

In [3]:
students_df.describe()

age        Medu        Fedu  traveltime   studytime    failures  \
count  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000   
mean    16.744222    2.514638    2.306626    1.568567    1.930663    0.221880   
std      1.218138    1.134552    1.099931    0.748660    0.829510    0.593235   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    2.000000    1.000000    1.000000    1.000000    0.000000   
50%     17.000000    2.000000    2.000000    1.000000    2.000000    0.000000   
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000   
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000   
mean     3.930663    3.180277    3.184900    1.502311    2.280431    3.536210   
std      0.955717    1.051093    1.175766    0.924834    1.284380    1.446259   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      4.000000    3.000000    2.000000    1.000000    1.000000    2.000000   
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000   
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  649.000000  649.000000  649.000000  649.000000  
mean     3.659476   11.399076   11.570108   11.906009  
std      4.640759    2.745265    2.913639    3.230656  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000   10.000000   10.000000   10.000000  
50%      2.000000   11.000000   11.000000   12.000000  
75%      6.000000   13.000000   13.000000   14.000000  
max     32.000000   19.000000   19.000000   19.000000

In [4]:
students_df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [5]:
# Create the bins in which Drinking levels will be held
bins = [0,1,2,3,4,5]

# Create the names for the five bins
group_names = ["Not at all", "Slightly", "Moderately", "Very", "Extremely"]

In [6]:
# Create column to contain new bins
students_df["Likelyhood to Drink"] = pd.cut(students_df["Walc"], bins, labels=group_names)
students_df

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
644     MS   F   19       R     GT3       T     2     3  services     other   
645     MS   F   18       U     LE3       T     3     1   teacher  services   
646     MS   F   18       U     GT3       T     1     1     other     other   
647     MS   M   17       U     LE3       T     3     1  services  services   
648     MS   M   18       R     LE3       T     3     2  services     other   

     ... freetime goout  Dalc  Walc  health absences  G1  G2  G3  \
0    ...        3     4     1     1       3        4   0  11  11   
1    ...        3     3     1     1       3        2   9  11  11   
2    ...        3     2     2     3       3        6  12  13  12   
3    ...        2     2     1     1       5        0  14  14  14   
4    ...        3     2     1     2       5        0  11  13  13   
..   ...      ...   ...   ...   ...     ...      ...  ..  ..  ..   
644  ...        4     2     1     2       5        4  10  11  10   
645  ...        3     4     1     1       1        4  15  15  16   
646  ...        1     1     1     1       5        6  11  12   9   
647  ...        4     5     3     4       2        6  10  10  10   
648  ...        4     1     3     4       5        4  10  11  11   

    Likelyhood to Drink  
0            Not at all  
1            Not at all  
2            Moderately  
3            Not at all  
4              Slightly  
..                  ...  
644            Slightly  
645          Not at all  
646          Not at all  
647                Very  
648                Very  

[649 rows x 34 columns]

In [7]:
# Drop unrelated columns
students_df = students_df.drop(['school','G1', 'G2', 'G3', 'Dalc', 'Walc'], axis=1)
students_df.head()

sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason  \
0   F   18       U     GT3       A     4     4  at_home   teacher  course   
1   F   17       U     GT3       T     1     1  at_home     other  course   
2   F   15       U     LE3       T     1     1  at_home     other   other   
3   F   15       U     GT3       T     4     2   health  services    home   
4   F   16       U     GT3       T     3     3    other     other    home   

   ... nursery  higher  internet  romantic famrel freetime goout health  \
0  ...     yes     yes        no        no      4        3     4      3   
1  ...      no     yes       yes        no      5        3     3      3   
2  ...     yes     yes       yes        no      4        3     2      3   
3  ...     yes     yes       yes       yes      3        2     2      5   
4  ...     yes     yes        no        no      4        3     2      5   

  absences Likelyhood to Drink  
0        4          Not at all  
1        2          Not at all  
2        6          Moderately  
3        0          Not at all  
4        0            Slightly  

[5 rows x 28 columns]

In [8]:
students_df.dtypes

sex                      object
age                       int64
address                  object
famsize                  object
Pstatus                  object
Medu                      int64
Fedu                      int64
Mjob                     object
Fjob                     object
reason                   object
guardian                 object
traveltime                int64
studytime                 int64
failures                  int64
schoolsup                object
famsup                   object
paid                     object
activities               object
nursery                  object
higher                   object
internet                 object
romantic                 object
famrel                    int64
freetime                  int64
goout                     int64
health                    int64
absences                  int64
Likelyhood to Drink    category
dtype: object

In [9]:
students_df.head()

sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason  \
0   F   18       U     GT3       A     4     4  at_home   teacher  course   
1   F   17       U     GT3       T     1     1  at_home     other  course   
2   F   15       U     LE3       T     1     1  at_home     other   other   
3   F   15       U     GT3       T     4     2   health  services    home   
4   F   16       U     GT3       T     3     3    other     other    home   

   ... nursery  higher  internet  romantic famrel freetime goout health  \
0  ...     yes     yes        no        no      4        3     4      3   
1  ...      no     yes       yes        no      5        3     3      3   
2  ...     yes     yes       yes        no      4        3     2      3   
3  ...     yes     yes       yes       yes      3        2     2      5   
4  ...     yes     yes        no        no      4        3     2      5   

  absences Likelyhood to Drink  
0        4          Not at all  
1        2          Not at all  
2        6          Moderately  
3        0          Not at all  
4        0            Slightly  

[5 rows x 28 columns]

In [10]:
students_df = pd.get_dummies(students_df)
students_df.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
0   18     4     4           2          2         0       4         3      4   
1   17     1     1           1          2         0       5         3      3   
2   15     1     1           1          2         0       4         3      2   
3   15     4     2           1          3         0       3         2      2   
4   16     3     3           1          2         0       4         3      2   

   health  ...  higher_yes  internet_no  internet_yes  romantic_no  \
0       3  ...           1            1             0            1   
1       3  ...           1            0             1            1   
2       3  ...           1            0             1            1   
3       5  ...           1            0             1            0   
4       5  ...           1            1             0            1   

   romantic_yes  Likelyhood to Drink_Not at all  Likelyhood to Drink_Slightly  \
0             0                               1                             0   
1             0                               1                             0   
2             0                               0                             0   
3             1                               1                             0   
4             0                               0                             1   

   Likelyhood to Drink_Moderately  Likelyhood to Drink_Very  \
0                               0                         0   
1                               0                         0   
2                               1                         0   
3                               0                         0   
4                               0                         0   

   Likelyhood to Drink_Extremely  
0                              0  
1                              0  
2                              0  
3                              0  
4                              0  

[5 rows x 57 columns]

In [32]:
# Reformat data (x-inputs, y labels)
data = students_df.values
X = data[:, 0:29]
y = data[:, 29]

y = y.reshape(-1, 1)
print(X)
print(y)

[[18  4  4 ...  0  0  1]
 [17  1  1 ...  1  0  0]
 [15  1  1 ...  1  0  0]
 ...
 [18  1  1 ...  1  0  0]
 [17  3  1 ...  0  1  0]
 [18  3  2 ...  1  0  0]]
[[1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]

In [33]:
print(X.shape)
print(y.shape)

(649, 29)
(649, 1)


In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)



## Data Preprocessing ##

In [14]:
from sklearn.preprocessing import StandardScaler

X_scaler = StandardScaler().fit(X_train)

In [15]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [16]:
from sklearn.preprocessing import LabelEncoder

# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
label_encoder.fit(y_test)
encoded_y_test = label_encoder.transform(y_test)
print(encoded_y_train)
print(encoded_y_test)

[1 1 1 1 0 0 0 1 1 0 1 1 1 0 1 0 0 1 0 0 0 1 0 0 1 1 1 1 1 1 1 1 0 0 1 1 0
 1 1 0 0 1 1 1 0 1 0 0 0 0 1 1 1 1 0 0 1 0 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1
 0 0 0 1 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0
 0 0 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 0 1 1 1 1 0 0 1 1 0 1 1 1 0 1 1 0 0 1 1
 1 1 0 0 1 1 0 1 1 1 1 1 0 1 0 1 0 1 1 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 0
 0 0 1 1 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 1 1 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0
 0 0 1 1 0 1 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 0 0 1 0 1 0 1
 1 0 1 0 1 0 1 0 1 0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1
 0 1 0 1 0 0 0 1 0 0 1 1 0 1 0 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 0 1 1
 1 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0 1 0 0 1 1 1 1 0 1 1 0 1 1 0 1 1 1 1 1 0 0
 1 1 0 0 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 0 1 1 1 0 1 1 1 0 1 1 0 0 0 0 0 0 0
 1 1 1 1 0 1 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 0 0 1 1 1
 1 1 1 1 0 1 1 1 0 1 0 1 0 0 0 1 1 1 1 0 1 1 0 1 0 0 1 1 1 0 0 0 1 0 0 1 0
 0 1 1 1 1]
[0 1 0 0 1 1 

C:\Users\jener\Anaconda3\envs\PythonWebMongo\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jener\Anaconda3\envs\PythonWebMongo\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [17]:
for label, original_class in zip(encoded_y_train, y):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

Original Class: [1]
Encoded Label: 1
------------
Original Class: [1]
Encoded Label: 1
------------
Original Class: [1]
Encoded Label: 1
------------
Original Class: [1]
Encoded Label: 1
------------
Original Class: [1]
Encoded Label: 0
------------
Original Class: [0]
Encoded Label: 0
------------
Original Class: [0]
Encoded Label: 0
------------
Original Class: [1]
Encoded Label: 1
------------
Original Class: [0]
Encoded Label: 1
------------
Original Class: [0]
Encoded Label: 0
------------
Original Class: [1]
Encoded Label: 1
------------
Original Class: [1]
Encoded Label: 1
------------
Original Class: [0]
Encoded Label: 1
------------
Original Class: [0]
Encoded Label: 0
------------
Original Class: [0]
Encoded Label: 1
------------
Original Class: [1]
Encoded Label: 0
------------
Original Class: [1]
Encoded Label: 0
------------
Original Class: [1]
Encoded Label: 1
------------
Original Class: [0]
Encoded Label: 0
------------
Original Class: [0]
Encoded Label: 0
------------


In [18]:
from keras.utils import to_categorical

# One-hot encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

Using TensorFlow backend.


## Create Deep Learning Model ##

In [19]:
from tensorflow.keras.models import Sequential

model = Sequential()

In [20]:
from tensorflow.keras.layers import Dense
number_inputs = 11
number_hidden_nodes = 15
model.add(Dense(units=number_hidden_nodes,
                activation='relu', input_dim=number_inputs))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [21]:
# add another layer??
number_classes = 5
model.add(Dense(units=number_classes, activation='relu'))

In [22]:
# add another layer??
number_classes = 5
model.add(Dense(units=number_classes, activation='softmax'))

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 15)                180       
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 80        
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 30        
Total params: 290
Trainable params: 290
Non-trainable params: 0
_________________________________________________________________


In [24]:
# Use categorical crossentropy for categorical data and mean squared error for regression
# Hint: your output layer in this example is using software for logistic regression (categorical)
# If your output layer activation was `linear` then you may want to use `mse` for loss
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [25]:
X_train_scaled.shape=(486,11)

In [26]:
# Fit (train) the model
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=50,
    shuffle=True,
    verbose=2
)

ValueError: A target array with shape (486, 2) was passed for an output of shape (None, 5) while using as loss `categorical_crossentropy`. This loss expects targets to have the same shape as the output.

## Quantify Trained Model ##

In [ ]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

## Save Trained Model ##

In [ ]:
# Save the model
model.save("voice_model_trained_2.h5")