# Final Project #

## Create the DataFrame ##

In [1]:
import pandas as pd
import numpy as mp

In [2]:
# Create a reference to the CSV and import it into a Pandas DataFrame
csv_path = "Resources/student-por.csv"
students_df = pd.read_csv(csv_path)
students_df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        4   0  11  11  
1      5        3      3     1     1      3        2   9  11  11  
2      4        3      2     2     3      3        6  12  13  12  
3      3        2      2     1     1      5        0  14  14  14  
4      4        3      2     1     2      5        0  11  13  13  

[5 rows x 33 columns]

In [3]:
students_df.describe()

age        Medu        Fedu  traveltime   studytime    failures  \
count  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000   
mean    16.744222    2.514638    2.306626    1.568567    1.930663    0.221880   
std      1.218138    1.134552    1.099931    0.748660    0.829510    0.593235   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    2.000000    1.000000    1.000000    1.000000    0.000000   
50%     17.000000    2.000000    2.000000    1.000000    2.000000    0.000000   
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000   
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  649.000000  649.000000  649.000000  649.000000  649.000000  649.000000   
mean     3.930663    3.180277    3.184900    1.502311    2.280431    3.536210   
std      0.955717    1.051093    1.175766    0.924834    1.284380    1.446259   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      4.000000    3.000000    2.000000    1.000000    1.000000    2.000000   
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000   
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  649.000000  649.000000  649.000000  649.000000  
mean     3.659476   11.399076   11.570108   11.906009  
std      4.640759    2.745265    2.913639    3.230656  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000   10.000000   10.000000   10.000000  
50%      2.000000   11.000000   11.000000   12.000000  
75%      6.000000   13.000000   13.000000   14.000000  
max     32.000000   19.000000   19.000000   19.000000

In [4]:
students_df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [5]:
# need to pull out Walc before get dummies on dataset - need Walc later to bin
pulled_Dalc = students_df[['Dalc']].copy()
pulled_Dalc

Dalc
0       1
1       1
2       2
3       1
4       1
..    ...
644     1
645     1
646     1
647     3
648     3

[649 rows x 1 columns]

In [6]:
# Drop unrelated columns and Walc
students_df = students_df.drop(['school','G1', 'G2', 'G3', 'Dalc', 'Walc'], axis=1)
students_df.head()

sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason  \
0   F   18       U     GT3       A     4     4  at_home   teacher  course   
1   F   17       U     GT3       T     1     1  at_home     other  course   
2   F   15       U     LE3       T     1     1  at_home     other   other   
3   F   15       U     GT3       T     4     2   health  services    home   
4   F   16       U     GT3       T     3     3    other     other    home   

   ... activities  nursery  higher  internet romantic famrel freetime goout  \
0  ...         no      yes     yes        no       no      4        3     4   
1  ...         no       no     yes       yes       no      5        3     3   
2  ...         no      yes     yes       yes       no      4        3     2   
3  ...        yes      yes     yes       yes      yes      3        2     2   
4  ...         no      yes     yes        no       no      4        3     2   

  health absences  
0      3        4  
1      3        2  
2      3        6  
3      5        0  
4      5        0  

[5 rows x 27 columns]

In [7]:
students_df.dtypes

sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
health         int64
absences       int64
dtype: object

In [8]:
students_df.head()

sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason  \
0   F   18       U     GT3       A     4     4  at_home   teacher  course   
1   F   17       U     GT3       T     1     1  at_home     other  course   
2   F   15       U     LE3       T     1     1  at_home     other   other   
3   F   15       U     GT3       T     4     2   health  services    home   
4   F   16       U     GT3       T     3     3    other     other    home   

   ... activities  nursery  higher  internet romantic famrel freetime goout  \
0  ...         no      yes     yes        no       no      4        3     4   
1  ...         no       no     yes       yes       no      5        3     3   
2  ...         no      yes     yes       yes       no      4        3     2   
3  ...        yes      yes     yes       yes      yes      3        2     2   
4  ...         no      yes     yes        no       no      4        3     2   

  health absences  
0      3        4  
1      3        2  
2      3        6  
3      5        0  
4      5        0  

[5 rows x 27 columns]

In [9]:
# perform get dummies on data set (less Walc) to binary encode for scaling
encoded_students_df = pd.get_dummies(students_df)
encoded_students_df.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
0   18     4     4           2          2         0       4         3      4   
1   17     1     1           1          2         0       5         3      3   
2   15     1     1           1          2         0       4         3      2   
3   15     4     2           1          3         0       3         2      2   
4   16     3     3           1          2         0       4         3      2   

   health  ...  activities_no  activities_yes  nursery_no  nursery_yes  \
0       3  ...              1               0           0            1   
1       3  ...              1               0           1            0   
2       3  ...              1               0           0            1   
3       5  ...              0               1           0            1   
4       5  ...              1               0           0            1   

   higher_no  higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  
0          0           1            1             0            1             0  
1          0           1            0             1            1             0  
2          0           1            0             1            1             0  
3          0           1            0             1            0             1  
4          0           1            1             0            1             0  

[5 rows x 52 columns]

In [10]:
# keep encoded df clean from y data for prediction purposes
working_students_df = encoded_students_df.copy()
working_students_df.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
0   18     4     4           2          2         0       4         3      4   
1   17     1     1           1          2         0       5         3      3   
2   15     1     1           1          2         0       4         3      2   
3   15     4     2           1          3         0       3         2      2   
4   16     3     3           1          2         0       4         3      2   

   health  ...  activities_no  activities_yes  nursery_no  nursery_yes  \
0       3  ...              1               0           0            1   
1       3  ...              1               0           1            0   
2       3  ...              1               0           0            1   
3       5  ...              0               1           0            1   
4       5  ...              1               0           0            1   

   higher_no  higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  
0          0           1            1             0            1             0  
1          0           1            0             1            1             0  
2          0           1            0             1            1             0  
3          0           1            0             1            0             1  
4          0           1            1             0            1             0  

[5 rows x 52 columns]

In [11]:
working_students_df.dtypes

age                  int64
Medu                 int64
Fedu                 int64
traveltime           int64
studytime            int64
failures             int64
famrel               int64
freetime             int64
goout                int64
health               int64
absences             int64
sex_F                uint8
sex_M                uint8
address_R            uint8
address_U            uint8
famsize_GT3          uint8
famsize_LE3          uint8
Pstatus_A            uint8
Pstatus_T            uint8
Mjob_at_home         uint8
Mjob_health          uint8
Mjob_other           uint8
Mjob_services        uint8
Mjob_teacher         uint8
Fjob_at_home         uint8
Fjob_health          uint8
Fjob_other           uint8
Fjob_services        uint8
Fjob_teacher         uint8
reason_course        uint8
reason_home          uint8
reason_other         uint8
reason_reputation    uint8
guardian_father      uint8
guardian_mother      uint8
guardian_other       uint8
schoolsup_no         uint8
s

In [12]:
pulled_Dalc.dtypes

Dalc    int64
dtype: object

In [13]:
# insert Walc back into encoded dataframe
working_students_df['Dalc']=pulled_Dalc['Dalc']
working_students_df

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  \
0     18     4     4           2          2         0       4         3   
1     17     1     1           1          2         0       5         3   
2     15     1     1           1          2         0       4         3   
3     15     4     2           1          3         0       3         2   
4     16     3     3           1          2         0       4         3   
..   ...   ...   ...         ...        ...       ...     ...       ...   
644   19     2     3           1          3         1       5         4   
645   18     3     1           1          2         0       4         3   
646   18     1     1           2          2         0       1         1   
647   17     3     1           2          1         0       2         4   
648   18     3     2           3          1         0       4         4   

     goout  health  ...  activities_yes  nursery_no  nursery_yes  higher_no  \
0        4       3  ...               0           0            1          0   
1        3       3  ...               0           1            0          0   
2        2       3  ...               0           0            1          0   
3        2       5  ...               1           0            1          0   
4        2       5  ...               0           0            1          0   
..     ...     ...  ...             ...         ...          ...        ...   
644      2       5  ...               1           1            0          0   
645      4       1  ...               0           0            1          0   
646      1       5  ...               1           0            1          0   
647      5       2  ...               0           1            0          0   
648      1       5  ...               0           1            0          0   

     higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  Dalc  
0             1            1             0            1             0     1  
1             1            0             1            1             0     1  
2             1            0             1            1             0     2  
3             1            0             1            0             1     1  
4             1            1             0            1             0     1  
..          ...          ...           ...          ...           ...   ...  
644           1            0             1            1             0     1  
645           1            0             1            1             0     1  
646           1            1             0            1             0     1  
647           1            0             1            1             0     3  
648           1            0             1            1             0     3  

[649 rows x 53 columns]

In [14]:
# Create the bins in which Drinking levels will be held
bins = [0,1,2,3,4,5]

# Create the names for the five bins
group_names = ["A.Not at all", "B.Slightly", "C.Moderately", "D.Very", "E.Extremely"]

In [15]:
# Create column to contain new bins
working_students_df["Likelyhood to Drink"] = pd.cut(working_students_df["Dalc"], bins, labels=group_names)
working_students_df = working_students_df.drop(['Dalc'], axis=1)

working_students_df

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  \
0     18     4     4           2          2         0       4         3   
1     17     1     1           1          2         0       5         3   
2     15     1     1           1          2         0       4         3   
3     15     4     2           1          3         0       3         2   
4     16     3     3           1          2         0       4         3   
..   ...   ...   ...         ...        ...       ...     ...       ...   
644   19     2     3           1          3         1       5         4   
645   18     3     1           1          2         0       4         3   
646   18     1     1           2          2         0       1         1   
647   17     3     1           2          1         0       2         4   
648   18     3     2           3          1         0       4         4   

     goout  health  ...  activities_yes  nursery_no  nursery_yes  higher_no  \
0        4       3  ...               0           0            1          0   
1        3       3  ...               0           1            0          0   
2        2       3  ...               0           0            1          0   
3        2       5  ...               1           0            1          0   
4        2       5  ...               0           0            1          0   
..     ...     ...  ...             ...         ...          ...        ...   
644      2       5  ...               1           1            0          0   
645      4       1  ...               0           0            1          0   
646      1       5  ...               1           0            1          0   
647      5       2  ...               0           1            0          0   
648      1       5  ...               0           1            0          0   

     higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  \
0             1            1             0            1             0   
1             1            0             1            1             0   
2             1            0             1            1             0   
3             1            0             1            0             1   
4             1            1             0            1             0   
..          ...          ...           ...          ...           ...   
644           1            0             1            1             0   
645           1            0             1            1             0   
646           1            1             0            1             0   
647           1            0             1            1             0   
648           1            0             1            1             0   

     Likelyhood to Drink  
0           A.Not at all  
1           A.Not at all  
2             B.Slightly  
3           A.Not at all  
4           A.Not at all  
..                   ...  
644         A.Not at all  
645         A.Not at all  
646         A.Not at all  
647         C.Moderately  
648         C.Moderately  

[649 rows x 53 columns]

In [16]:
working_students_df["Likelyhood to Drink"].value_counts()

A.Not at all    451
B.Slightly      121
C.Moderately     43
E.Extremely      17
D.Very           17
Name: Likelyhood to Drink, dtype: int64

In [17]:
# Reformat data (x-inputs, y labels)
data = working_students_df.values
X = data[:, 0:52]
y = data[:, 52]

# y = y.reshape(-1, 1)
print(X)
print(y)

[[18 4 4 ... 0 1 0]
 [17 1 1 ... 1 1 0]
 [15 1 1 ... 1 1 0]
 ...
 [18 1 1 ... 0 1 0]
 [17 3 1 ... 1 1 0]
 [18 3 2 ... 1 1 0]]
['A.Not at all' 'A.Not at all' 'B.Slightly' 'A.Not at all' 'A.Not at all'
 'A.Not at all' 'A.Not at all' 'A.Not at all' 'A.Not at all'
 'A.Not at all' 'A.Not at all' 'A.Not at all' 'A.Not at all'
 'A.Not at all' 'A.Not at all' 'A.Not at all' 'A.Not at all'
 'A.Not at all' 'B.Slightly' 'A.Not at all' 'A.Not at all' 'A.Not at all'
 'A.Not at all' 'B.Slightly' 'A.Not at all' 'A.Not at all' 'A.Not at all'
 'B.Slightly' 'A.Not at all' 'E.Extremely' 'C.Moderately' 'A.Not at all'
 'A.Not at all' 'A.Not at all' 'A.Not at all' 'A.Not at all'
 'A.Not at all' 'A.Not at all' 'A.Not at all' 'A.Not at all'
 'A.Not at all' 'B.Slightly' 'A.Not at all' 'A.Not at all' 'B.Slightly'
 'A.Not at all' 'A.Not at all' 'A.Not at all' 'B.Slightly' 'A.Not at all'
 'B.Slightly' 'A.Not at all' 'C.Moderately' 'B.Slightly' 'D.Very'
 'A.Not at all' 'A.Not at all' 'A.Not at all' 'A.Not at all'
 

In [18]:
print(X.shape)
print(y.shape)

(649, 52)
(649,)


In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10)

## Data Preprocessing ##

In [20]:
# Create the SVC Model
from sklearn.svm import SVC 
model = SVC(kernel='linear')
model

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [21]:
# Create the GridSearch estimator along with a parameter object containing the values to adjust
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10, 50],
              'gamma': [0.0001, 0.0005, 0.001, 0.005]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [22]:
# Fit the model using the grid search estimator. 
# This will take the SVC model and try each combination of parameters
grid.fit(X_train, y_train)

C:\Users\jener\Anaconda3\envs\PythonWebMongo\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.1s remaining:    0.0s


Fitting 3 folds for each of 16 candidates, totalling 48 fits
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.671, total=   0.1s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.654, total=   0.1s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.694, total=   0.1s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ................... C=1, gamma=0.0005, score=0.671, total=   0.1s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ................... C=1, gamma=0.0005, score=0.654, total=   0.1s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ................... C=1, gamma=0.0005, score=0.694, total=   0.1s
[CV] C=1, gamma=0.001 ................................................
[CV] ...........

[Parallel(n_jobs=1)]: Done  48 out of  48 | elapsed:   16.8s finished
C:\Users\jener\Anaconda3\envs\PythonWebMongo\lib\site-packages\sklearn\model_selection\_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='linear',
                           max_iter=-1, probability=False, random_state=None,
                           shrinking=True, tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [1, 5, 10, 50],
                         'gamma': [0.0001, 0.0005, 0.001, 0.005]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [23]:
# List the best parameters for this dataset
print(grid.best_params_)

{'C': 1, 'gamma': 0.0001}


In [24]:
# List the best score
print(grid.best_score_)

0.6728395061728395


In [25]:
# Make predictions with the hypertuned model
predictions = grid.predict(X_test)

In [26]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=["A.Not at all", "B.Slightly", "C.Moderately", "D.Very", "E.Extremely"]))

              precision    recall  f1-score   support

A.Not at all       0.67      0.98      0.80       107
  B.Slightly       1.00      0.03      0.06        32
C.Moderately       0.00      0.00      0.00        15
      D.Very       0.00      0.00      0.00         4
 E.Extremely       0.00      0.00      0.00         5

    accuracy                           0.65       163
   macro avg       0.33      0.20      0.17       163
weighted avg       0.64      0.65      0.54       163



C:\Users\jener\Anaconda3\envs\PythonWebMongo\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [27]:
report = classification_report(y_test, predictions, output_dict=True)

In [28]:
grid_class_df = pd.DataFrame(report).transpose()
grid_class_df

precision    recall  f1-score     support
A.Not at all   0.673077  0.981308  0.798479  107.000000
B.Slightly     1.000000  0.031250  0.060606   32.000000
C.Moderately   0.000000  0.000000  0.000000   15.000000
D.Very         0.000000  0.000000  0.000000    4.000000
E.Extremely    0.000000  0.000000  0.000000    5.000000
accuracy       0.650307  0.650307  0.650307    0.650307
macro avg      0.334615  0.202512  0.171817  163.000000
weighted avg   0.638155  0.650307  0.536053  163.000000

In [30]:
grid_class_df.to_csv('Resources/grid_class_Dalc_likelyhood.csv')